// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: (() => {
      const candidates = [
        process.env["DATABASE_URL"],
        process.env["POSTGRES_URL_NON_POOLING"],
        process.env["POSTGRES_URL"],
        process.env["POSTGRES_PRISMA_URL"],
      ];
      for (const url of candidates) {
        if (url?.startsWith("postgres://") || url?.startsWith("postgresql://")) return url;
      }
      return process.env["DATABASE_URL"];
    })(),
  },
});
